server:
  port: 8080

spring:
  application:
    name: dopp-api
  profiles:
    active: dev   # 기본 실행 환경 (운영 배포 시 prd로 변경)

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.dopp.doppapi.dto
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
